FROM eclipse-temurin:17.0.4.1_1-jre as Builder
WORKDIR extracted
ADD target/*.jar app.jar
RUN java -Djarmode=layertools -jar app.jar extract

FROM eclipse-temurin:17.0.4.1_1-jre
WORKDIR application
COPY --from=Builder extracted/dependencies/ ./
COPY --from=Builder extracted/spring-boot-loader/ ./
COPY --from=Builder extracted/snapshot-dependencies/ ./
COPY --from=Builder extracted/application/ ./
EXPOSE 8080
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
